server:
  port: 28088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Login
    username: root
    password: LuvuubyRK*Jason1258
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
